trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFilesOverSSH@0
  displayName: 'Securely copy files to the remote machine'
  inputs:
    sshEndpoint: 'techpathlocalserver'
    sourceFolder: '$(System.DefaultWorkingDirectory)/path/to/html/files'
    targetFolder: '/var/www/farooq.techpath.pro/public_html'

- task: SSH@0
  inputs:
    sshEndpoint: 'techpathlocalserver'
    runOptions: 'commands'
    commands: |
      echo "Starting";
      # Additional deployment steps if needed
      echo "Deploying index.html file completed."
    readyTimeout: '20000'
