name: Unzip on Server

on:
  release:
    types: created

jobs:
  unzip_on_server:
    runs-on: ubuntu-latest
    steps:
      - name: Unzip on Server
        run: |
          sshpass -p 'sanjeev123' ssh server@202.176.1.150 "unzip -q /media/server/data-5121/laye/archive.zip -d /media/server/data-5121/laye"
        env:
          SSH_USER: 'server'
          SSH_PASSWORD: 'sanjeev123'
          SERVER_IP: '202.176.1.150'
