trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  steps:
  - script: npm install
    displayName: 'Install Dependencies'

  - script: npm audit fix --force
    displayName: 'Fix Security Vulnerabilities'

  - script: npm install --save-dev @babel/plugin-proposal-private-property-in-object@1.0.0
    displayName: 'Add @babel/plugin-proposal-private-property-in-object to devDependencies'

  - script: npm run build
    displayName: 'Build React App'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'build'
      artifactName: 'react-app'
    displayName: 'Publish Build Artifacts'
