- name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ${{ github.workspace }}/archive.zip

    - name: Upload to NAS
      uses: appleboy/scp-action@master
      with:
        host: ${{ 192.168.1.3 }}
        username: ${{ techpathadmin }}
        password: ${{ newLappy@29092022 }}
        source: ${{ github.workspace }}/archive.zip
        target: '/volume1/sharedemp'
