trigger:
  - main
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: CopyFilesOverSSH@0
  displayName: 'Securely copy files to the remote machine'
    inputs:
      sshEndpoint: '192.168.1.3'
      sourceFolder: '$(Build.ArtifactStagingDirectory)'
      targetFolder: '/volume1/sharedemp'
