name: Deploy to Local Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Archive Repository
        run: |
          zip -r my_repo.zip .
        working-directory: ${{ github.workspace }}

      - name: Deploy to Local Server
        run: |
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i "" my_repo.zip techpathadmin@192.168.1.3:/volume1/sharedemp
        env:
          SSH_PRIVATE_KEY_PATH: ""
