name: SSH Deploy GitHub repo on server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: SSH Deploy
      uses: Rxinui/ssh-deploy-repo-action@v1.1
      with:
        ssh-user: 'server'
        ssh-password: 'sanjeev123'
        ssh-domain: '202.176.1.150'
        target-directory: /media/server/data-5121/layer
        target-branch: main
        git-clone-by: ssh
        pre-command: |
          # Command lines to execute before deployment (optional)
        post-command: |
          # Command lines to execute after deployment (optional)
