trigger:
  - main
 
pool:
  vmImage: 'ubuntu-latest'
 
steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '/volume1/sharedemp'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: CopyFilesOverSSH@192.168.1.3
  displayName: 'Securely copy files to the remote machine'
  inputs:
    sshEndpoint: 'techpathinternalserver'
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    targetFolder: '/volume1/sharedemp'
- task: SSH@192.168.1.3
  inputs:
    sshEndpoint: 'techpathinternalserver'
    runOptions: 'commands'
    commands: |
      echo "Starting";
      cd /volume1/sharedemp/ && unzip -o $(Build.BuildId).zip
      source /volume1/sharedemp/venv/bin/activate && pip3 install -r /volume1/sharedemp/s/requirements.txt;
      rm /volume1/sharedemp/$(Build.BuildId).zip
    readyTimeout: '20000'
