trigger:
  - main
 
pool:
  vmImage: 'ubuntu-latest'  
steps:
- task: "ArchiveFiles@github"
  inputs:
    rootFolderOrFile: '$(github.workspace)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: ""
    replaceExistingArchive: true
- task: CopyFilesOver@NasServer
  displayName: 'Securely copy files to the remote machine'
  inputs:
    sshEndpoint: '192.168.1.3'
   sourceFolder: ""
   targetFolder: '/volume1/sharedemp/'
