trigger:
  - main
pool:
  vmImage: 'ubuntu-latest'
steps:
 - task: ArchiveFiles@2
   inputs:
    rootFolderOrFile: '/volume1/sharedemp'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '/build.zip'
    replaceExistingArchive: true
 - task: CopyFilesOverSSH@0
   displayName: 'Securely copy files to the remote machine'
   inputs:
   sshEndpoint: '192.168.1.3'
    sourceFolder: ''  # Update this line to the correct source folder
    targetFolder: '/volume1/sharedemp'
