name: Zip and Deploy

on:
  push:
    branches:
      - main

jobs:
  zip_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Archive Repository
        run: |
          zip -r ${{ github.workspace }}/archive.zip .
        working-directory: ${{ github.workspace }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ${{ github.workspace }}/archive.zip

      - name: Debug
        run: ls $GITHUB_WORKSPACE  # List contents of the directory for debugging

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: '202.176.1.150'
          username: 'server'
          password: 'sanjeev123'
          script: |
            cd /media/server/data-5121/layer
            unzip -o archive.zip
