name: Archive and upload by ssh

on:
  push:
    branches:
      - main

jobs:
  archive_and_upload_by_ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Archive Repository
        run: |
          zip -r ${{ github.workspace }}/archive.zip .
        working-directory: ${{ github.workspace }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ${{ github.workspace }}/archive.zip

      - name: Deploy to Local Server
        uses: appleboy/scp-action@main
        with:
          host: 192.168.1.3
          username: techpathadmin
          password: newLappy@29092022
          local_file: ${{ github.workspace }}/archive.zip
          remote_path: /volume1/sharedemp
