trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/repo.zip'
    replaceExistingArchive: true

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: '192.168.1.3' # Replace with the name of your SSH service connection
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    contents: '**/*.zip'
    targetFolder: '/volume1/sharedemp'
