name: SSH Server Deploy
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: '202.176.1.150'
          port: '22'
          username: 'server'
          password: 'sanjeev123'
          scp_source: /home/runner/work/deployrepo/deployrepo/archive.zip
          scp_target: /media/server/data-5121/laye
