name: Archive and Deploy

on:
  push:
    branches:
      - main

jobs:
  archive_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Archive Repository
        run: |
          zip -r ${{ github.workspace }}/archive.zip .
        working-directory: ${{ github.workspace }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ${{ github.workspace }}/archive.zip

      - name: Deploy to Local Server
        uses: appleboy/scp-action@master
        with:
         host: '202.176.1.150'
         username: 'server'
         password: 'sanjeev123'
         local_file: ${{ github.workspace }}/archive.zip
         remote_path: /media/server/data-5121/laye
