name: Zip and Deploy

on:
  push:
    branches:
      - main

jobs:
  zip_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Archive Repository
        run: |
          zip -r ${{ github.workspace }}/archive.zip .
        working-directory: ${{ github.workspace }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{ github.workspace }}/archive.zip
          
          script: |
            scp /home/runner/work/deployrepo/deployrepo/archive.zip server@202.176.1.150:/media/server/data-5121/layer
