trigger:
  - main
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(github.workspace)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: CopyFilesOverSSH@0
  displayName: 'Securely copy files to the remote machine'
  inputs:
    sshEndpoint: 
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    targetFolder: '/volume1/sharedemp'
