name: ssh-pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Archive Files
        run: |
          zip -r deployment.zip .

      - name: SSH Deploy
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with: 
          host: "192.168.1.3"
          port: 22 # optional, default is 22
          user: techpathadmin
          pass: newLappy@29092022 # optional
          connect_timeout: 30 # optional, default is 30s
          script: |
            # Your deployment script or commands go here
            # For example:
            echo "Hello, deploying your application!"
            cd /volume1/sharedemp
            mkdir -p /home/github/test/test1
            mkdir -p /home/github/test/test2

            # Upload the zip file
            scp -P 22 $GITHUB_WORKSPACE/deployment.zip techpathadmin@192.168.1.3:/volume1/sharedemp

            # Unzip the file
            ssh -p 22 techpathadmin@192.168.1.3 cd /volume1/sharedemp && unzip -o deployment.zip

            # Add any additional deployment steps as needed
