name: ssh-pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create ZIP Archive
        run: |
          zip -r deployment.zip .
        working-directory: github.workspace

      - name: SSH Deploy
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with: 
          host: "192.168.1.3"
          port: "22" # optional, default is 22
          user: "techpathadmin"
          pass: "newLappy@29092022" # optional
          connect_timeout: 30 # optional, default is 30s
          script: |
            # Your deployment script or commands go here
            # For example:
            echo "Hello, deploying your application!"
            unzip -o /volume1/sharedemp/deployment.zip -d /volume1/sharedemp
            mkdir -p /home/github/test/test1
            mkdir -p /home/github/test/test2
          zip: true
