trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: CompressAndUpload
  displayName: 'Compress and Upload to NAS'
  steps:
  - checkout: self

  - script: |
      sudo apt-get install zip
      zip -r repo.zip <path_to_your_repo>
    displayName: 'Compress Repo'

  - publish: $(System.DefaultWorkingDirectory)/repo.zip
    artifact: drop
    displayName: 'Publish Artifact'

- job: UploadToNAS
  displayName: 'Upload to NAS'
  dependsOn: CompressAndUpload
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: '**/*.zip'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: SCP@0
    inputs:
      host: '192.168.1.3'
      username: 'techpathadmin'
      password: 'newLappy@29092022'
      port: '22'
      sourceFolder: '$(Build.ArtifactStagingDirectory)'
      targetFolder: '/volume1/sharedemp'
    displayName: 'Upload to NAS'
