name: Archive and Copy to Local Server
 
on:
  push:
    branches:
      - main
 
jobs:
  archive_and_copy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
 
    - name: Archive Repository
      run: |
        zip -r ${{ github.workspace }}/archive.zip .
      working-directory: ${{ github.workspace }}
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ${{ github.workspace }}/archive.zip
 
    - name: Copy to Local Server
      uses: appleboy/scp-action@master
      with:
        host: '192.168.1.3'
        username: 'techpathadmin'
        password: 'newLappy@29092022'
        source: ${{ github.workspace }}/archive.zip
        target: '/volume1/sharedemp'
