name: Zip and Deploy

on:
  push:
    branches:
      - main

jobs:
  zip_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Archive Repository
        run: |
          zip -r ${{ github.workspace }}/archive.zip .
        working-directory: ${{ github.workspace }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ${{ github.workspace }}/archive.zip

      - name: SSH Server Deploy
        run: |
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> $HOME/.ssh/known_hosts
          ssh server@202.176.1.150 'unzip -o /media/server/data-5121/laye/archive.zip -d /media/server/data-5121/laye'
        env:
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
