name: Unzip Artifact

on:
  workflow_run:
    workflows: ["Zip and Deploy"]
    types:
      - completed

jobs:
  unzip_artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: /media/server/data-5121/laye

      - name: Unzip Artifact
        run: unzip -q /media/server/data-5121/laye/archive.zip 
