name: ssh pipelines
 
on:
  push:
    branches:
      - main
 
jobs:
  ssh-pipelines:
    runs-on: ubuntu-latest
 
    steps:
      - name: ssh pipelines
        uses: techpathadmin@192.168.1.3:/volume1/sharedemp  # Replace with the correct branch or tag name
 
        # Define environment variables
        env:
          WELCOME: "ssh pipeline"
 
        # Define input parameters for the action
        with:
          host: 192.168.1.3  # Replace with the correct secret
          user: techpathadmin  # Replace with the correct secret
          pass: newLappy@29092022  # Replace with the correct secret
          port: 22  # Replace with the correct secret
          connect_timeout: 10s
 
          # Provide valid shell commands in the script
          script: |
            (rm -rf /home/github/test || true)
            ls -la  
            echo $WELCOME 
            mkdir -p /home/github/test/test1 &&
            mkdir -p /home/github/test/test2 &&
